---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: fraud-det-v31
spec:
  type: NodePort
  selector:
    app: backend
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30880

# triton ClusterIP service is defined in deployments.yaml
# dcgm-exporter service removed — using gpu-operator's existing nvidia-dcgm-exporter service
